# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-  repo: https://github.com/ansible/ansible-lint
   rev: v6.19.0
   hooks:
    -  id: ansible-lint
